apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-demo-new
  labels:
    app: k8s-demo-app
data:
  PORT: "8080"
  ENVIRONMENT: "production"
  DATABASE_URL: "postgres://db:5432/app"
  APP_VERSION: "v1.0.0"
  # Configuration file example
  app.properties: |
    server.port=8080
    server.environment=production
    database.url=postgres://db:5432/app
    logging.level=info