apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: k8s-demo-new
  labels:
    app: k8s-demo-app
type: Opaque
data:
  # API_SECRET: "super-secret-key" (base64 encoded)
  API_SECRET: c3VwZXItc2VjcmV0LWtleQ==
  # Database credentials
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  # JWT secret
  JWT_SECRET: and0LXNlY3JldC10b2tlbi1rZXk=