apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo-pod
  namespace: k8s-demo-new
  labels:
    app: k8s-demo-app
    version: v1.0.0
spec:
  containers:
  - name: app
    image: k8s-demo-app:v1.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      name: http
    env:
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: PORT
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENVIRONMENT
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DATABASE_URL
    - name: APP_VERSION
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_VERSION
    - name: API_SECRET
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: API_SECRET
    # Health checks
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    # Resource limits
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"