apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-demo-pv
  labels:
    type: local
    app: k8s-demo-app
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/tmp/k8s-demo-data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-demo-pvc
  namespace: k8s-demo-new
  labels:
    app: k8s-demo-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deployment-with-volume
  namespace: k8s-demo-new
  labels:
    app: k8s-demo-app
    variant: with-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app
      variant: with-volume
  template:
    metadata:
      labels:
        app: k8s-demo-app
        variant: with-volume
    spec:
      containers:
      - name: app
        image: k8s-demo-app:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_URL
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_VERSION
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_SECRET
        - name: DATA_DIR
          value: "/data"
        volumeMounts:
        - name: data-storage
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: k8s-demo-pvc