apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-demo
  labels:
    app: k8s-demo-app
data:
  PORT: "8080"
  ENVIRONMENT: "kubernetes"
  DATABASE_URL: "postgres://postgres:5432/demo"
  LOG_LEVEL: "info"
  FEATURE_FLAGS: |
    {
      "new_ui": true,
      "beta_features": false,
      "analytics": true
    } 