apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-demo-app-sa
  namespace: k8s-demo
  labels:
    app: k8s-demo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-demo-app-role
  namespace: k8s-demo
  labels:
    app: k8s-demo-app
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-demo-app-rolebinding
  namespace: k8s-demo
  labels:
    app: k8s-demo-app
subjects:
- kind: ServiceAccount
  name: k8s-demo-app-sa
  namespace: k8s-demo
roleRef:
  kind: Role
  name: k8s-demo-app-role
  apiGroup: rbac.authorization.k8s.io 