apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: k8s-demo
  labels:
    app: k8s-demo-app
type: Opaque
data:
  # API_SECRET: "super-secret-key-123" (base64 encoded)
  API_SECRET: c3VwZXItc2VjcmV0LWtleS0xMjM=
  # DATABASE_PASSWORD: "secure-password" (base64 encoded)  
  DATABASE_PASSWORD: c2VjdXJlLXBhc3N3b3Jk
  # JWT_SECRET: "jwt-signing-key" (base64 encoded)
  JWT_SECRET: and0LXNpZ25pbmcta2V5 